services:
  carenest-api:
    container_name: carenest-api
    restart: always
    image: carenest-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=carenestSWD;Username=postgres;Password=postgres
      - RUN_MIGRATIONS=true
    depends_on:
      - db
      
  db:
    image: postgres:13
    container_name: postgres-carenest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: carenestSWD
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    